from numpy import array
import math

class Planet:
    """
    the class to control a celestial body

    todo David use this class for calculating the physics of the planets
        the GUI will use the position, radius and color to draw it to the display
        the tag will be automatically generated by the GUI to keep track of the shape that is drawn
        feel free to add more attributes/functions as needed for physics
    """

    def __init__(self, position: list, radius: float, color: str):
        """
        creates the planet with the given attributes

        :param position: the position of the planet in space
        :param radius: the radius of the planet
        :param color: the color of the planet
        """

        self.position = array(position)
        self.radius = radius
        self.orbital_radius = math.sqrt(self.position[0]**2 + self.position[1]**2)
        self.period = self.orbital_radius**(3/2) / 1000
        self.color = color
        self.tag = None
